# Generated by Django 2.2.3 on 2019-07-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='div',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('dividend', models.TextField()),
                ('dividend_size', models.BigIntegerField()),
                ('divisor', models.TextField()),
                ('divisor_size', models.BigIntegerField()),
                ('runtime', models.BigIntegerField()),
                ('return_val', models.BooleanField()),
            ],
        ),
    ]
