# Generated by Django 2.2.3 on 2019-07-30 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigint_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='div',
            unique_together={('dividend', 'divisor')},
        ),
    ]
