# Generated by Django 2.2.3 on 2019-07-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigint_app', '0002_auto_20190730_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='div_rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisor', models.TextField()),
                ('divisor_size', models.BigIntegerField()),
                ('rule', models.TextField()),
                ('rule_size', models.BigIntegerField()),
            ],
        ),
    ]
