# Generated by Django 2.2.3 on 2019-07-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigint_app', '0003_div_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='div_rule',
            name='id',
        ),
        migrations.AlterField(
            model_name='div_rule',
            name='divisor',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
