# Generated by Django 2.2.3 on 2019-07-30 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigint_app', '0004_auto_20190730_2052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='div_rule',
        ),
    ]
