# Author: Jake Mathai
# Purpose: Docker container config
version: "3"
services:
  py:
    container_name: py
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    command: uvicorn api.main:app
    ports:
      - 80:80
    expose:
      - 80
    environment:
      - UVICORN_WORKERS=2
      - UVICORN_LOOP=uvloop
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=80
      - UVICORN_LOG_LEVEL=debug
    logging:
        driver: "json-file"
        options:
            max-size: "1m"
